
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A BATCH CANCELAR CONSULTAR DATA DATE DISPONIBILIDADE EQ ESTADO FILTRO HORA_FIM HORA_INICIO LABORATORIO NE NEWLINE NUMBER PERIODO PISO RESERVAR SALA STRING TIME TIPOprograma : reservarreservar : RESERVAR recurso STRING DATA DATE HORA_INICIO TIME HORA_FIM TIMErecurso : SALA\n                | LABORATORIO '
    
_lr_action_items = {'RESERVAR':([0,],[3,]),'$end':([1,2,13,],[0,-1,-2,]),'SALA':([3,],[5,]),'LABORATORIO':([3,],[6,]),'STRING':([4,5,6,],[7,-3,-4,]),'DATA':([7,],[8,]),'DATE':([8,],[9,]),'HORA_INICIO':([9,],[10,]),'TIME':([10,12,],[11,13,]),'HORA_FIM':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'reservar':([0,],[2,]),'recurso':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> reservar','programa',1,'p_programa','parser.py',5),
  ('reservar -> RESERVAR recurso STRING DATA DATE HORA_INICIO TIME HORA_FIM TIME','reservar',9,'p_reservar','parser.py',10),
  ('recurso -> SALA','recurso',1,'p_recurso','parser.py',21),
  ('recurso -> LABORATORIO','recurso',1,'p_recurso','parser.py',22),
]
